import os
from dotenv import load_dotenv, find_dotenv

load_dotenv(find_dotenv())

REGEX_POLE_FILTERS = {
    "Poleet":r"[pP][oO][lL][eE][eE][tT]",
    "Poeet":r"[pP][oO][eE][eE][tT]",
    "Pole":r".*[pP][oO][lL][eE].*",
    "Oro":r"[oO][rR][oO].*",
    "Plata":r"[pP][lL][aA][tT][aA].*",
    "Bronce":r"[bB][rR][oO][nN][cC][eE].*",
    "Hora":r"[hH][oO][rR][aA].*",
    "Alarma Magnas":r"[aA][lL][aA][rR][mM][aA]\s[mM][aA][ñÑ][aA][sS]",
    "Fail":r"[fF][aA][iI][lL]",
    "Mastil":r"[mM][aA][sS][tT][iI][lL]",
}

REGEX_POLE_TYPE = {
    "Alarma Magnas":r"^alarma magnas",
    "Fail Canario":r"^bronce canario",
    "Fail Canario":r"^fail canario",
    "Fracapole":r"^bronce$",
    "Fracapole":r"^fail$",
    "Fracapole":r"^fracapole",
    "Hora Porro":r"^hora porro",
    "Hora π (3.141592653589793238)":r"^hora pi",
    "Hora π (3.141592653589793238)":r"^hora π",
    "Mastil":r"^mastil",
    "Mastil":r"^mástil",
    "Neopole":r"^neopole",
    "Pole Canaria":r"^oro canario",
    "Subpole Canaria":r"^plata canario",
    "Poeet":r"^poeet$",
    "Pole Andaluza":r"^pole andaluza",
    "Pole Binaria":r"^pole binaria",
    "Pole Boix":r"^pole boix",
    "Pole Básica":r"^pole básica",
    "Pole Cafelito":r"^pole cafelito",
    "Pole Canaria":r"^pole canaria",
    "Pole Clásica":r"^pole clásica",
    "Pole Contemporánea":r"^pole contemporánea",
    "Pole Cotizante":r"^pole cotizante",
    "Pole CRX":os.getenv("CRX_REGEX"),
    "Pole CRX":r"^pole crx",
    "Pole Crítica":r"^pole crítica",
    "Pole Eterna":r"^pole eterna",
    "Pole Fran":r"^pole fran",
    "Pole Germà":r"^pole germà",
    "Pole Germà":r"^pole germa",
    "Pole Insomnio":r"^pole insomnio",
    "Pole Letal":r"^pole letal",
    "Pole Magnas":r"^pole magnas",
    "Pole Mistica":r"^pole mística",
    "Pole Montero":r"^pole montero",
    "Pole Máxima":r"^pole máxima",
    "Pole Mínima":r"^pole mínima",
    "Pole Presko":r"^pole presko",
    "Pole Toakiza":r"^pole toakiza",
    "Pole Ucraniana":r"^pole ucraniana",
    "Poleet":r"^poleet",
    "Polen":r"^polen$",
    "Polerdaka":r"^polerdaka",
    "Polerdakardamenaka":r"^polerdakardamenaka",
    "Polerdamen":r"^polerdamen",
    "Postpole":r"^postpole",
    "Prepole":r"^prepole",
    "Pseudopole":r"^pseudopole",
    "Subpole Canaria":r"^subpole canaria",
    "Pole Cuck":r"^pole milel",
    "Pole Cuck":r"^pole cuquel",
    "Pole Cuck":r"^pole culel",
    "Pole Cuck":r"^pole cuck",
    "Pole Cuck":r"^pole cukel",
    "Pole Cuck":r"^pole milel tennis",
    "Pole Cuck":r"^pole miquel rami",
    os.getenv("LPG"):r"^pole lpg",
    os.getenv("LPG"):r"^pole maria",
    os.getenv("LPG"):os.getenv("LPG_REGEX"),
    # Leave at the end
    "Subpole":r"^plata$",
    "Subpole":r"^subpole$",
    "Pole":r"^oro$",
    "Pole":r"^pole$",
}

POLE_WITH_COIN = {
    "Pole Binaria":"Germà Coin 🍁",
    "Pole Boix":"Germà Coin 🍁",
    "Pole Germa":"Germà Coin 🍁",
    "Pole Fran":"Triggered Coin 💀",
    "Pole Ucraniana":"Triggered Coin 💀",
    "Pole Montero":"Triggered Coin 💀",
    "Pole Toakiza":"Triggered Coin 💀",
    "Pole Presko":"Triggered Coin 💀",
    "Pole Crítica":"Critic Coin 🔝",
    "Fracapole":"Clown Coin 🤡",
    "Pole Magnas":"Clown Coin 🤡",
    "Mastil":"Clown Coin 🤡",
    "Pole Montero":"Clown Coin 🤡",
    "Pole Cafelito":"Cafelito necesario ☕",
    "Pole Cuck":"Cuck Coin 🐐",
    os.getenv("LPG"):"Tagliatella Coin 🍝",
    "Pole CRX":os.getenv("CRX_COIN"),
    "Polen":os.getenv("CRX_COIN"),
}

POLE_WITH_COIN_LIST = list(POLE_WITH_COIN.keys())

POLE_POINTS = {
    "Alarma Magnas":0.5,
    "Bronce Canario":1.25,
    "Bronce":2.5,
    "Fail":2.5,
    "Fracapole":1,
    "Hora Porro":4,
    "Hora π (3.141592653589793238)":3,
    "Mastil":0,
    "Neopole":0.05,
    "Oro Canario":5,
    "Oro":10,
    "Plata Canario":2.5,
    "Plata":5,
    "Poeet":1,
    "Pole Andaluza":0.5,
    "Pole Binaria":0.05,
    "Pole Boix":0.05,
    "Pole Básica":0.05,
    "Pole Cafelito":0.5,
    "Pole Canaria":5,
    "Pole Clásica":0.05,
    "Pole Contemporánea":0.05,
    "Pole Cotizante":1.5,
    "Pole CRX":0.1,
    "Pole CRX":0.1,
    "Pole Crítica":0.05,
    "Pole Eterna":0.05,
    "Pole Fran":0.05,
    "Pole Germà":0.05,
    "Pole Insomnio":0.3,
    "Pole Letal":0.05,
    "Pole Magnas":0.05,
    "Pole Mistica":0.05,
    "Pole Montero":0.05,
    "Pole Máxima":0.05,
    "Pole Mínima":0.05,
    "Pole Presko":0.05,
    "Pole Toakiza":1,
    "Pole Ucraniana":0.05,
    "Pole":10,
    "Poleet":1,
    "Polen":0.1,
    "Polerdaka":0.05,
    "Polerdakardamenaka":0.05,
    "Polerdamen":0.05,
    "Postpole":0.05,
    "Prepole":0.05,
    "Pseudopole":0.05,
    "Subpole Canaria":2.5,
    "Subpole":5,
    "Pole Cuck":0.01,
    os.getenv("LPG"):0.01,
}

MF_FIELDS = {
    "message_from_id":"tg_user_id",
    "message_from_is_bot":"tg_is_bot",
    "message_from_first_name":"tg_first_name",
    "message_from_username":"tg_username",
    "message_chat_id":"tg_group_id",
    "message_chat_title":"tg_group_title",
    "message_chat_type":"tg_group_type",
    "message_date":"tg_date_time",
    "message_text":"tg_message",
    "message_entities_type":"tg_entity_type",
}

MF_FIELDS_KEYS = MF_FIELDS.keys()

REGEX_FILTERS = {
    **REGEX_POLE_FILTERS,
}

