import os
from dotenv import load_dotenv, find_dotenv

load_dotenv(find_dotenv())

REGEX_POLE_FILTERS = {
    "Poleet":r"[pP][oO][lL][eE][eE][tT]",
    "Poeet":r"[pP][oO][eE][eE][tT]",
    "Pole":r".*[pP][oO][lL][eE].*",
    "Oro":r"[oO][rR][oO].*",
    "Plata":r"[pP][lL][aA][tT][aA].*",
    "Bronce":r"[bB][rR][oO][nN][cC][eE].*",
    "Hora":r"[hH][oO][rR][aA].*",
    "Alarma Magnas":r"[aA][lL][aA][rR][mM][aA]\s[mM][aA][ñÑ][aA][sS]",
    "Fail":r"[fF][aA][iI][lL]",
    "Mastil":r"[mM][aA][sS][tT][iI][lL]",
}

REGEX_POLE_TYPE = {
    "Subpole":r"subpole",
    "Fracapole":r"fracapole",
    "Pole Canaria":r"pole canaria",
    "Oro Canario":r"oro canario",
    "Subpole Canaria":r"subpole canaria",
    "Plata Canario":r"plata canario",
    "Bronce Canario":r"bronce canario",
    "Hora π (3.141592653589793238)":r"hora pi",
    "Pole Insomnio":r"pole insomnio",
    "Hora Porro":r"hora porro",
    "Pole Cotizante":r"pole cotizante",
    "Pole Cafelito":r"pole cafelito",
    "Pole Andaluza":r"pole andaluza",
    "Neopole":r"neopole",
    "Postpole":r"postpole",
    "Prepole":r"prepole",
    "Polerdakardamenaka":r"polerdakardamenaka",
    "Polerdaka":r"polerdaka",
    "Polerdamen":r"polerdamen",
    "Pole Básica":r"pole básica",
    "Pole Magnas":r"pole magnas",
    "Pole CRX":os.getenv("CRX_REGEX"),
    "Pole Contemporánea":r"pole contemporánea",
    "Pole Letal":r"pole letal",
    "Pole Máxima":r"pole máxima",
    "Pole Mínima":r"pole mínima",
    "Polen":r"polen",
    "Pole Ucraniana":r"pole ucraniana",
    "Pole Montero":r"pole montero",
    "Pole Toakiza":r"pole toakiza",
    "Pole Presko":r"pole presko",
    "Pseudopole":r"pseudopole",
    "Pole Mistica":r"pole mística",
    "Pole Clásica":r"pole clásica",
    "Pole Eterna":r"pole eterna",
    "Pole Binaria":r"pole binaria",
    "Pole Boix":r"pole boix",
    "Pole Germà":r"pole germà",
    "Pole Fran":r"pole fran",
    "Pole Crítica":r"pole crítica",
    "Mastil":r"mastil",
    "Pole CRX":r"pole crx",
    **REGEX_POLE_FILTERS,
}

POLE_WITH_COIN = {
    "Pole Binaria":"Germà Coin 🍁",
    "Pole Boix":"Germà Coin 🍁",
    "Pole Germa":"Germà Coin 🍁",
    "Pole Fran":"Triggered Coin 💀",
    "Pole Ucraniana":"Triggered Coin 💀",
    "Pole Montero":"Triggered Coin 💀",
    "Pole Toakiza":"Triggered Coin 💀",
    "Pole Presko":"Triggered Coin 💀",
    "Pole Crítica":"Critic Coin 🔝",
    "Fracapole":"Clown Coin 🤡",
    "Pole Magnas":"Clown Coin 🤡",
    "Mastil":"Clown Coin 🤡",
    "Pole Montero":"Clown Coin 🤡",
    "Pole Cafelito":"Cafelito necesario ☕",
    "Pole CRX":os.getenv("CRX_COIN"),
    "Polen":os.getenv("CRX_COIN"),
    os.getenv("CRX"):os.getenv("CRX_COIN"),
}

POLE_WITH_COIN_LIST = list(POLE_WITH_COIN.keys())

POLE_POINTS = {
    "Subpole":5,
    "Fracapole":1,
    "Pole Canaria":5,
    "Oro Canario":5,
    "Subpole Canaria":2.5,
    "Plata Canario":2.5,
    "Bronce Canario":1.25,
    "Hora π (3.141592653589793238)":3,
    "Pole Insomnio":0.3,
    "Hora Porro":4,
    "Pole Cotizante":1.5,
    "Pole Cafelito":0.5,
    "Pole Andaluza":0.5,
    "Neopole":0.05,
    "Postpole":0.05,
    "Prepole":0.05,
    "Polerdakardamenaka":0.05,
    "Polerdaka":0.05,
    "Polerdamen":0.05,
    "Pole Básica":0.05,
    "Pole Magnas":0.05,
    "Pole CRX":0.1,
    "Pole Contemporánea":0.05,
    "Pole Letal":0.05,
    "Pole Máxima":0.05,
    "Pole Mínima":0.05,
    "Polen":0.1,
    "Pole Ucraniana":0.05,
    "Pole Montero":0.05,
    "Pole Toakiza":1,
    "Pole Presko":0.05,
    "Pseudopole":0.05,
    "Pole Mistica":0.05,
    "Pole Clásica":0.05,
    "Pole Eterna":0.05,
    "Pole Binaria":0.05,
    "Pole Boix":0.05,
    "Pole Germà":0.05,
    "Pole Fran":0.05,
    "Pole Crítica":0.05,
    "Poleet":1,
    "Poeet":1,
    "Pole":10,
    "Oro":10,
    "Plata":5,
    "Bronce":2.5,
    "Alarma Magnas":0.5,
    "Fail":2.5,
    "Pole CRX":0.1,
    "Mastil":0,
}

MF_FIELDS = {
    "message_from_id":"tg_user_id",
    "message_from_is_bot":"tg_is_bot",
    "message_from_first_name":"tg_first_name",
    "message_from_username":"tg_username",
    "message_chat_id":"tg_group_id",
    "message_chat_title":"tg_group_title",
    "message_chat_type":"tg_group_type",
    "message_date":"tg_date_time",
    "message_text":"tg_message",
    "message_entities_type":"tg_entity_type",
}

MF_FIELDS_KEYS = MF_FIELDS.keys()

REGEX_FILTERS = {
    **REGEX_POLE_FILTERS,
}

